/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateMessageObjectData = {
  message: string;
};

export class CreateMessageObject extends Error {
  /** The original data that was passed to this error instance. */
  data$: CreateMessageObjectData;

  constructor(err: CreateMessageObjectData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.name = "CreateMessageObject";
  }
}

/** @internal */
export const CreateMessageObject$inboundSchema: z.ZodType<
  CreateMessageObject,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
})
  .transform((v) => {
    return new CreateMessageObject(v);
  });

/** @internal */
export type CreateMessageObject$Outbound = {
  message: string;
};

/** @internal */
export const CreateMessageObject$outboundSchema: z.ZodType<
  CreateMessageObject$Outbound,
  z.ZodTypeDef,
  CreateMessageObject
> = z.instanceof(CreateMessageObject)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateMessageObject$ {
  /** @deprecated use `CreateMessageObject$inboundSchema` instead. */
  export const inboundSchema = CreateMessageObject$inboundSchema;
  /** @deprecated use `CreateMessageObject$outboundSchema` instead. */
  export const outboundSchema = CreateMessageObject$outboundSchema;
  /** @deprecated use `CreateMessageObject$Outbound` instead. */
  export type Outbound = CreateMessageObject$Outbound;
}
