/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

/**
 * Invalid id error
 */
export type GetUserResponseBodyData = {
  success: boolean;
  error: components.CreateError;
};

/**
 * Invalid id error
 */
export class GetUserResponseBody extends Error {
  success: boolean;
  error: components.CreateError;

  /** The original data that was passed to this error instance. */
  data$: GetUserResponseBodyData;

  constructor(err: GetUserResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.success = err.success;
    this.error = err.error;

    this.name = "GetUserResponseBody";
  }
}

/** @internal */
export const GetUserResponseBody$inboundSchema: z.ZodType<
  GetUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: components.CreateError$inboundSchema,
})
  .transform((v) => {
    return new GetUserResponseBody(v);
  });

/** @internal */
export type GetUserResponseBody$Outbound = {
  success: boolean;
  error: components.CreateError$Outbound;
};

/** @internal */
export const GetUserResponseBody$outboundSchema: z.ZodType<
  GetUserResponseBody$Outbound,
  z.ZodTypeDef,
  GetUserResponseBody
> = z.instanceof(GetUserResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: components.CreateError$outboundSchema,
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserResponseBody$ {
  /** @deprecated use `GetUserResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetUserResponseBody$inboundSchema;
  /** @deprecated use `GetUserResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetUserResponseBody$outboundSchema;
  /** @deprecated use `GetUserResponseBody$Outbound` instead. */
  export type Outbound = GetUserResponseBody$Outbound;
}
